`timescale 1ns / 1ps
//Module for Store instructions - data to be written to reg file is generated by this module
module Loads(
    input [31:0] instr,
    input [31:0] drdata,
    output reg[31:0] out
);
    
	
    always@(instr or daddr or drdata)
    begin   
        
        case(instr[14:12])
        3'b000: out = {24{drdata[7]}, drdata[7:0]};    //LB
        3'b001: out = {16{drdata[15]}, drdata[15:0]};  //LH
        3'b010: out = drdata;                          //LW
        3'b100: out = {24'b0, drdata[7:0]};            //LBU
        3'b101: out = {16'b0, drdata[15:0]};           //LHU
        endcase
    end
endmodule